# Site settings
title: "Sungwon Cho"
description: "A Simple Resume of Sungwon Cho"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sungwon Cho"
resume_nickname:                "Sam Jo; 뀨냥이"
resume_title:                   "DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "samjo.nyang@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82-10-1234-5678"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello World! I am a devops engineer working at Hyperconnect. I had my first chance to learn how to code a program when I was 12. Ever since then, I am in love with it! I enjoy learning new techs and solving new problems!</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_projects:        true
resume_section_skills:          true
resume_section_research:        true
resume_section_recognition:     true
resume_section_education:       true
resume_section_associations:    false
resume_section_links:           false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/samjo-nyang"
  resume_facebook_url:          "https://fb.com/sambradjo"
  resume_twitter_url:           "https://twitter.com/samjo_nyang"
  resume_linkedin_url:          "https://linkedin.com/in/sambradjo"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
